export const PROJECT_STATUS = {
    PLANNING: "Planning",
    COMPLETED: "Completed"
}

export const ACTIVITIES = [
    { value: "SIGHTSEEING", label: "Sightseeing" },
    { value: "DINING", label: "Dining" },
    { value: "ADVENTURE/SPORTS", label: "Adventure/Sports" },
    { value: "LEISURE/RELAXATION", label: "Leisure/Relaxation" },
    { value: "CULTURAL EXPERIENCES", label: "Cultural Experiences" },
    { value: "NIGHTLIFE", label: "Nightlife" },
    { value: "SHOPPING", label: "Shopping" },
    { value: "WILDLIFE/NATURE", label: "Wildlife/Nature" },
    { value: "HIKING/TREKKING", label: "Hiking/Trekking" },
    { value: "BEACH/COASTAL", label: "Beach/Coastal" },
    { value: "HISTORICAL SITES", label: "Historical Sites" },
    { value: "MUSEUMS/ART GALLERIES", label: "Museums/Art Galleries" },
    { value: "FESTIVALS/EVENTS", label: "Festivals/Events" },
    { value: "WELLNESS (SPA/YOGA)", label: "Wellness (Spa/Yoga)" },
    { value: "EDUCATIONAL/LEARNING", label: "Educational/Learning" },
    { value: "RELIGIOUS/SPIRITUAL", label: "Religious/Spiritual" },
    { value: "VINEYARDS/WINE TASTING", label: "Vineyards/Wine Tasting" },
    { value: "AMUSEMENT/WATER PARKS", label: "Amusement/Water Parks" },
    { value: "CAMPING", label: "Camping" },
    { value: "BOATING/SAILING", label: "Boating/Sailing" },
    { value: "SKIING/SNOWBOARDING", label: "Skiing/Snowboarding" },
    { value: "PHOTOGRAPHY", label: "Photography" },
    { value: "VOLUNTEERING", label: "Volunteering" },
    { value: "MUSIC/CONCERTS", label: "Music/Concerts" },
    { value: "LOCAL MARKETS/FAIRS", label: "Local Markets/Fairs" },
    { value: "FOOD/CULINARY TOURS", label: "Food/Culinary Tours" },
    { value: "SCENIC DRIVES/RIDES", label: "Scenic Drives/Rides" },
    { value: "GARDENS/PARKS", label: "Gardens/Parks" },
    { value: "FILM/CINEMA", label: "Film/Cinema" },
    { value: "LITERATURE/READING", label: "Literature/Reading" },
    { value: "THEATRE/PERFORMANCES", label: "Theatre/Performances" },
    { value: "ARCHITECTURE", label: "Architecture" },
    { value: "GAMING/CASINOS", label: "Gaming/Casinos" },
    { value: "FITNESS/GYM", label: "Fitness/Gym" },
    { value: "COOKING CLASSES", label: "Cooking Classes" },
    { value: "WORKSHOPS/CRAFTS", label: "Workshops/Crafts" },
    { value: "FARMS/AGRICULTURE", label: "Farms/Agriculture" },
    { value: "ASTRONOMY/STARGAZING", label: "Astronomy/Stargazing" },
    { value: "SCUBA DIVING/SNORKELING", label: "Scuba Diving/Snorkeling" },
    { value: "BIRD WATCHING", label: "Bird Watching" }
  ];
  